# Generated by Django 3.1 on 2020-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
